String
LOGIN_SCREEN = '/LogInScreen',
    SIGNUP_SCREEN = '/SignUpScreen',
    ANIMATED_SPLASH = '/SplashScreen',
    HOME_SCREEN = '/HomeScreen',
    FORGOT_SCREEN = '/ForgotScreen',
    VERIFY_SCREEN = '/VerifyScreen',
    CART_SCREEN = '/CartScreen',
    ORDER_SCREEN = '/OrderScreen',
    PREFERENCE_SCREEN = '/PreferenceScreen',
    PROFILE_SCREEN = '/ProfileScreen',
    SUBSCRIPTION_SCREEN = '/ScriptionScreen',
    ABOUT_SCREEN = '/AboutScreen',
    CONTACT_SCREEN = '/ContactScreen',
    FAQ_SCREEN = '/FaqScreen',
    FEEDBACK_SCREEN = '/FeedbackScreen',
    CHEF_SCREEN = '/ChefScreen',
    FOOD_SCREEN = '/FoodScreen',
    LOCATION_SCREEN = '/LocationScreen',
    SEARCH_SCREEN = '/SearchScreen',
    SORT_SCREEN = '/SortScreen';

